# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ResponseMnemonicModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, privatekey_wif=None, address=None, balance_satoshi=None):  # noqa: E501
        """ResponseMnemonicModel - a model defined in OpenAPI

        :param code: The code of this ResponseMnemonicModel.  # noqa: E501
        :type code: int
        :param textdata_list: The textdata_list of this ResponseMnemonicModel.  # noqa: E501
        :type textdata_list: List[str]
        """
        self.openapi_types = {
            'code': int,
            'textdata_list': List[str]
        }

        self.attribute_map = {
            'code': 'code',
            'textdata_list': 'textdata_list'
        }

        self._code = code
        self._textdata_list = textdata_list

    @classmethod
    def from_dict(cls, dikt) -> 'ResponseMnemonicModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResponseMnemonicModel of this ResponseMnemonicModel.  # noqa: E501
        :rtype: ResponseMnemonicModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this ResponseMnemonicModel.


        :return: The code of this ResponseMnemonicModel.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ResponseMnemonicModel.


        :param code: The code of this ResponseMnemonicModel.
        :type code: int
        """

        self._code = code

    @property
    def textdata_list(self):
        """Gets the textdata_list of this ResponseMnemonicModel.


        :return: The textdata_list of this ResponseMnemonicModel.
        :rtype: List[str]
        """
        return self._textdata_list

    @textdata_list.setter
    def textdata_list(self, textdata_list):
        """Sets the textdata_list of this ResponseMnemonicModel.


        :param textdata_list: The textdata_list of this ResponseMnemonicModel.
        :type textdata_list: List[str]
        """

        self._textdata_list = textdata_list
